# Generated by Django 3.0.6 on 2020-05-23 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(max_length=256)),
                ('organization_name', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('Beginner', 'Начинающий'), ('Frequent buyer', 'Опытный покупатель')], default='Beginner', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, unique=True, verbose_name='Никнейм'),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('seller_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Seller')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.seller',),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('founder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Founder')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.founder',),
        ),
    ]
