# Generated by Django 3.0.6 on 2020-05-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200523_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('Начинающий', 'Начинающий'), ('Опытный покупатель', 'Опытный покупатель')], default='Beginner', max_length=100),
        ),
    ]
