# Generated by Django 3.0.6 on 2020-05-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='updated',
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
